#!/bin/bash

set -u

jsFiles=($(git diff-tree --no-commit-id --name-only -r HEAD | grep -Ee '\.ts$'))

if [ "${#jsFiles[@]}" -ne 0 ]; then
  pnpm exec eslint --fix -- "${jsFiles[@]}"
  pnpm exec prettier --write -- "${jsFiles[@]}"
  git add -- "${jsFiles[@]}"
fi
